
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author btorralba
 */
public class RailroadFrame extends javax.swing.JFrame implements Observateur {


    private static final ImageIcon DESERT = new ImageIcon("./src/imgs/Texture 100x100/desert.png");
    private static final ImageIcon DESERTSELECTION = new ImageIcon("./src/imgs/Texture 100x100/desertSelection.png");
    
    private static final ImageIcon VILLE = new ImageIcon("./src/imgs/Texture 100x100/ville.png");
    private static final ImageIcon VILLESELECTION = new ImageIcon("./src/imgs/Texture 100x100/villeSelection.png");
    
    
    private static final ImageIcon RAILV = new ImageIcon("./src/imgs/Texture 100x100/railsV.png");
    private static final ImageIcon RAILH = new ImageIcon("./src/imgs/Texture 100x100/railsH.png");
    private static final ImageIcon RAIL = new ImageIcon("./src/imgs/Texture 100x100/railsH.png");
    
    ArrayList<int[]> trajet = new ArrayList();
    
    /**
     * Creates new form RailroadFrame
     */
    JLabel[][] jboard;
    Modele modele;
    
    public RailroadFrame(Modele m) {
        initComponents();
        
        modele=m;
        
        
    // Pannel disposé en grille 8*8
        panelJeu.setLayout(new GridLayout(8,8));
        
    // board composé de jlabel    
        jboard = new JLabel[8][8];
         for(int i=0;i<8;i++){
            for(int j=0;j<8;j++){
                // init case desert
                jboard[i][j] = new JLabel(DESERT);
                panelJeu.add(jboard[i][j]);
               jboard[i][j].addMouseListener(
                new CaseControler(i,j));
                }
   
            }
         

         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJeu = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelJeuLayout = new javax.swing.GroupLayout(panelJeu);
        panelJeu.setLayout(panelJeuLayout);
        panelJeuLayout.setHorizontalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelJeuLayout.setVerticalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jButton2.setText("SUPPRIMER RAILS");

        jButton1.setText("PLACER RAILS");
        jButton1.setActionCommand("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.getAccessibleContext().setAccessibleName("placerRails");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bouton placer rail
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            modele.placerRails(trajet);
        } catch (InterruptedException ex) {
            Logger.getLogger(RailroadFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                
                //new RailroadFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panelJeu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void avertirSelectionVille(int i, int j, Ville v) {
        
        jboard[i][j].setIcon(v.getTexture());
    }
    
    
    @Override
    public void avertirChangementCase(int i, int j, Case c) {
        jboard[i][j].setIcon(c.getTexture());
    }
    
    @Override
    public void avertirTrainTrue(int i, int j, Case c) {
        jboard[i][j].setIcon(((Rail)c).getTextureTrain());
        
    }
    
        public void avertirTrainFalse(int i, int j, Case c) {
        jboard[i][j].setIcon(((Rail)c).getTexture());
        
    }
    
    

    
    
    
    //Mouvement souris
     class CaseControler extends MouseAdapter {
        int i;
        int j;

        public CaseControler(int _i, int _j){
            i = _i;
            j = _j;
        }

    //action de clic
        @Override
        public void mouseClicked(MouseEvent e)
        {
            int tab[] = {i,j};
            
            System.out.println(i + " " + j);
            
            //Si case non selectionné on change icone, et on enregistre ses coordonnées dans trajet
            if (jboard[i][j].getIcon()==DESERT){
               jboard[i][j].setIcon(DESERTSELECTION); 
               trajet.add(tab);
            }
            
            //Si case selectionné on change iconne et on vide trajet
            else if (jboard[i][j].getIcon()==DESERTSELECTION){
                jboard[i][j].setIcon(DESERT);
                trajet.clear();
            }
            
            //Si clic sur une ville et quelle n'est pas selectionné (attibut selection) on change iconne on selectionne et ajout a trajet
            else if (modele.getCase(i, j) instanceof Ville && ((Ville)modele.getCase(i, j)).isSelection()==false){
                jboard[i][j].setIcon(modele.getCase(i, j).getTextureSelection());
                ((Ville)modele.getCase(i, j)).setSelection(true);
                trajet.add(tab);
            }
            
            //Si ville deja selectionne on change iconne on change selection a false et on vide trajet
            else if (modele.getCase(i, j) instanceof Ville && ((Ville)modele.getCase(i, j)).isSelection()){
                jboard[i][j].setIcon(modele.getCase(i, j).getTexture());
                 modele.getCase(i, j).setSelection(false);
                 trajet.clear();
            }
 
            //Si on clique sur un rail pas selectionné on change iconne et on change selection
            if (modele.getCase(i, j) instanceof Rail && ((Rail)modele.getCase(i, j)).isSelection()==false){
               jboard[i][j].setIcon(modele.getCase(i, j).getTextureSelection());
               modele.getCase(i, j).setSelection(true);
            }
            
            
            else if (modele.getCase(i, j) instanceof Rail && ((Rail)modele.getCase(i, j)).isSelection()){
                jboard[i][j].setIcon(modele.getCase(i, j).getTexture());
                 modele.getCase(i, j).setSelection(false);
            
            }
            
     
        }
     }

}
