
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author btorralba
 */
public class RailroadFrame extends javax.swing.JFrame implements Observateur {


    private static final ImageIcon DESERT = new ImageIcon("./src/imgs/Texture 100x100/desert.png");
    private static final ImageIcon DESERTSELECTION = new ImageIcon("./src/imgs/Texture 100x100/desertSelection.png");
    
    private static final ImageIcon VILLE = new ImageIcon("./src/imgs/Texture 100x100/ville.png");
    private static final ImageIcon VILLESELECTION = new ImageIcon("./src/imgs/Texture 100x100/villeSelection.png");
    
    
    private static final ImageIcon RAILV = new ImageIcon("./src/imgs/Texture 100x100/railsV.png");
    private static final ImageIcon RAILH = new ImageIcon("./src/imgs/Texture 100x100/railsH.png");
    private static final ImageIcon RAIL = new ImageIcon("./src/imgs/Texture 100x100/railsH.png");
    
    ArrayList<int[]> trajet = new ArrayList();
    
    /**
     * Creates new form RailroadFrame
     */
    JLabel[][] jboard;
    Modele modele;
    
    public RailroadFrame(Modele m) {
        initComponents();
        
        modele=m;
        
        
    // Pannel disposé en grille 8*8
        panelJeu.setLayout(new GridLayout(7,7));
        
    // board composé de jlabel    
        jboard = new JLabel[7][7];
         for(int i=0;i<7;i++){
            for(int j=0;j<7;j++){
                // init case desert
                jboard[i][j] = new JLabel(DESERT);
                panelJeu.add(jboard[i][j]);
               jboard[i][j].addMouseListener(
                new CaseControler(i,j));
                }
   
            }
         
       
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelJeu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelLimoges = new javax.swing.JLabel();
        jLabelLimogesLait = new javax.swing.JLabel();
        jLabelLimogesLaitQ = new javax.swing.JLabel();
        jLabelLimogesFer = new javax.swing.JLabel();
        jLabelLimogesFerQ = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelLimogesPlastiqueQ = new javax.swing.JLabel();
        jLabelToulouse = new javax.swing.JLabel();
        jLabelToulouseLaitQ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelToulouseFer = new javax.swing.JLabel();
        jLabelToulouseFerQ = new javax.swing.JLabel();
        jLabelToulousePlastiqueQ = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelServianLaitQ = new javax.swing.JLabel();
        jLabelServianFerQ = new javax.swing.JLabel();
        jLabelServianPlastiqueQ = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaInformations = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 51, 0));
        setForeground(java.awt.Color.white);
        setResizable(false);

        panelJeu.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout panelJeuLayout = new javax.swing.GroupLayout(panelJeu);
        panelJeu.setLayout(panelJeuLayout);
        panelJeuLayout.setHorizontalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelJeuLayout.setVerticalGroup(
            panelJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(175, 122, 68));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PLACER RAILS");
        jButton1.setActionCommand("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SUPPRIMER RAILS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextPane1.setText("Score :");
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jTextPane1);

        jLabelLimoges.setText("Hill Valley");

        jLabelLimogesLait.setText("Cereales :");

        jLabelLimogesFer.setText("Fer :");

        jLabel6.setText("Bois :");

        jLabelToulouse.setText("Santa Fe");

        jLabelToulouseLaitQ.setText("jLabel8");

        jLabel1.setText("Cereales :");

        jLabelToulouseFer.setText("Fer :");

        jLabelToulouseFerQ.setText("jLabel9");

        jLabelToulousePlastiqueQ.setText("jLabel10");

        jLabel7.setText("Bois :");

        jLabel2.setText("Carson City :");

        jLabel5.setText("Cereales :");

        jLabelServianLaitQ.setText("jLabel11");

        jLabelServianFerQ.setText("jLabel12");

        jLabelServianPlastiqueQ.setText("jLabel13");

        jLabel3.setText("Bois :");

        jLabel4.setText("Fer :");

        jTextAreaInformations.setColumns(20);
        jTextAreaInformations.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextAreaInformations.setLineWrap(true);
        jTextAreaInformations.setRows(5);
        jScrollPane2.setViewportView(jTextAreaInformations);

        jLabel8.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Informations :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelServianLaitQ)
                                        .addComponent(jLabelServianFerQ)
                                        .addComponent(jLabelServianPlastiqueQ)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelLimogesFer)
                                        .addComponent(jLabelLimogesLait)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabelLimoges)
                                        .addComponent(jLabelToulouse))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelLimogesLaitQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelLimogesFerQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelLimogesPlastiqueQ, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelToulouseLaitQ)
                                    .addGap(8, 8, 8))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabelToulouseFer)
                                            .addGap(1, 1, 1)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelToulouseFerQ)
                                        .addComponent(jLabelToulousePlastiqueQ))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addGap(24, 24, 24))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLimoges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLimogesLaitQ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLimogesLait, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLimogesFerQ, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLimogesFer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelLimogesPlastiqueQ, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelToulouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelToulouseLaitQ))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelToulouseFer)
                    .addComponent(jLabelToulouseFerQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelToulousePlastiqueQ))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelServianLaitQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelServianFerQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelServianPlastiqueQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.getAccessibleContext().setAccessibleName("placerRails");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Bouton placer rail
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            modele.placerRails(trajet);
        } catch (InterruptedException ex) {
            Logger.getLogger(RailroadFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    modele.supprimerRails(trajet);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RailroadFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                
                //new RailroadFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelLimoges;
    private javax.swing.JLabel jLabelLimogesFer;
    private javax.swing.JLabel jLabelLimogesFerQ;
    private javax.swing.JLabel jLabelLimogesLait;
    private javax.swing.JLabel jLabelLimogesLaitQ;
    private javax.swing.JLabel jLabelLimogesPlastiqueQ;
    private javax.swing.JLabel jLabelServianFerQ;
    private javax.swing.JLabel jLabelServianLaitQ;
    private javax.swing.JLabel jLabelServianPlastiqueQ;
    private javax.swing.JLabel jLabelToulouse;
    private javax.swing.JLabel jLabelToulouseFer;
    private javax.swing.JLabel jLabelToulouseFerQ;
    private javax.swing.JLabel jLabelToulouseLaitQ;
    private javax.swing.JLabel jLabelToulousePlastiqueQ;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaInformations;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel panelJeu;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void avertirSelection(int i, int j, Case c) {
        
        jboard[i][j].setIcon(c.getTextureSelection());
    }
    
    @Override
    public void avertirDeselection(int i, int j, Case c){
        jboard[i][j].setIcon(c.getTexture());
    }
    
    @Override
    public void avertirChangementCase(int i, int j, Case c) {
        jboard[i][j].setIcon(c.getTexture());
    }
    
    @Override
    public void avertirTrainTrue(int i, int j, Case c) {
        jboard[i][j].setIcon(((Rail)c).getTextureTrain());
        
    }
    
    public void avertirInformation(String s){
        //jTextAreaInformations.setText("null");
        jTextAreaInformations.setText(s);
    }
    
    public void avertirTrainFalse(int i, int j, Case c) {
        jboard[i][j].setIcon(((Rail)c).getTexture());
        
    }
        
    public void avertirCreationRessource(){
       
        jLabelLimogesLaitQ.setText(Integer.toString(modele.villes.get(0).getStock().get(0).getQuantite()));
        jLabelLimogesFerQ.setText(Integer.toString(modele.villes.get(0).getStock().get(1).getQuantite()));
        jLabelLimogesPlastiqueQ.setText(Integer.toString(modele.villes.get(0).getStock().get(2).getQuantite()));
        
        
        jLabelToulouseFerQ.setText(Integer.toString(modele.villes.get(1).getStock().get(0).getQuantite()));
        jLabelToulouseLaitQ.setText(Integer.toString(modele.villes.get(1).getStock().get(1).getQuantite()));
        jLabelToulousePlastiqueQ.setText(Integer.toString(modele.villes.get(1).getStock().get(2).getQuantite()));
        
        jLabelServianPlastiqueQ.setText(Integer.toString(modele.villes.get(2).getStock().get(0).getQuantite()));
        jLabelServianLaitQ.setText(Integer.toString(modele.villes.get(2).getStock().get(1).getQuantite()));
        jLabelServianFerQ.setText(Integer.toString(modele.villes.get(2).getStock().get(2).getQuantite()));
        
        
    }
        
    
    

    
    
    
    //Mouvement souris
     class CaseControler extends MouseAdapter {
        int i;
        int j;

        public CaseControler(int _i, int _j){
            i = _i;
            j = _j;
        }

    //action de clic
        @Override
        public void mouseClicked(MouseEvent e)
        {
            int tab[] = {i,j};
            
            System.out.println(i + " " + j);
            
            //Si case non selectionné on change icone, et on enregistre ses coordonnées dans trajet
            if (modele.getCase(i, j).isSelection()==false){
                modele.getCase(i, j).setSelection(true);
               //jboard[i][j].setIcon(modele.getCase(i, j).getTextureSelection()); 
                avertirSelection(i, j, modele.getCase(i, j));
               trajet.add(tab);
            }
            
            
            //Si case selectionné on change iconne et on vide trajet
           // else if (jboard[i][j].getIcon()==DESERTSELECTION){
           //     jboard[i][j].setIcon(DESERT);
            else {
                //jboard[i][j].setIcon(modele.getCase(i, j).getTexture()); 
                avertirDeselection(i, j, modele.getCase(i, j));
                modele.getCase(i, j).setSelection(false);
                trajet.clear();
            }
            
          /*  //Si clic sur une ville et quelle n'est pas selectionné (attibut selection) on change iconne on selectionne et ajout a trajet
            else if (modele.getCase(i, j) instanceof Ville && ((Ville)modele.getCase(i, j)).isSelection()==false){
                jboard[i][j].setIcon(modele.getCase(i, j).getTextureSelection());
                ((Ville)modele.getCase(i, j)).setSelection(true);
                trajet.add(tab);
            }
            
            //Si ville deja selectionne on change iconne on change selection a false et on vide trajet
            else if (modele.getCase(i, j) instanceof Ville && ((Ville)modele.getCase(i, j)).isSelection()){
                jboard[i][j].setIcon(modele.getCase(i, j).getTexture());
                 modele.getCase(i, j).setSelection(false);
                 trajet.clear();
            }
 
            //Si on clique sur un rail pas selectionné on change iconne et on change selection
            if (modele.getCase(i, j) instanceof Rail && ((Rail)modele.getCase(i, j)).isSelection()==false){
               jboard[i][j].setIcon(modele.getCase(i, j).getTextureSelection());
               modele.getCase(i, j).setSelection(true);
            }
            
            
            else if (modele.getCase(i, j) instanceof Rail && ((Rail)modele.getCase(i, j)).isSelection()){
                jboard[i][j].setIcon(modele.getCase(i, j).getTexture());
                 modele.getCase(i, j).setSelection(false);
            
            }*/
            
     
        }
     }

}
